import Head from "next/head";
import React from "react";
import { useForm } from "react-hook-form";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";

const Search = () => {
  const { register, handleSubmit } = useForm();
  const onSubmit = (data) => {
    console.log(data);
  };

  const { status } = useSession();
  const router = useRouter();
  if (status === "unauthenticated") {
    router.push("/login");
  }

  return (
    <>
      <Head>
        <title>Books | Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto bg-slate-900 px-14 py-5 min-w-full">
        <form onSubmit={handleSubmit(onSubmit)}>
          <h1 className="text-center font-bold text-white text-3xl">
            Search Books
          </h1>
          <div className="bg-white items-center justify-between w-full flex rounded-full shadow-lg px-2 py-1 mb-5 sticky mt-5">
            <input
              className="font-bold uppercase rounded-full w-full py-4 pl-4 text-gray-700 bg-gray-100 leading-tight focus:outline-none focus:shadow-outline lg:text-sm text-xs"
              type="text"
              placeholder="Search"
              {...register("term")}
            />

            <button
              type="submit"
              className="hover:bg-gray-600 p-2 bg-slate-900 cursor-pointer mx-2 rounded-full"
            >
              <svg
                className="w-6 h-6 text-white"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fillRule="evenodd"
                  d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                  clipRule="evenodd"
                />
              </svg>
            </button>
          </div>
        </form>
      </div>
    </>
  );
};

export default Search;
